[package]
name = "w5500-regsim"
version = "0.1.0-alpha.5"
authors = ["Alex Martens <alexmgit@protonmail.com>"]
edition = "2021"
repository = "https://github.com/newAM/w5500-regsim-rs"
license = "MIT"
description = "Register simulation for the Wiznet W5500 internet offload chip."
readme = "README.md"
keywords = ["W5500", "wiznet"]
categories = ["embedded", "development-tools"]
homepage = "https://github.com/newAM/w5500-regsim-rs"

[badges]
maintenance = { status = "experimental" }

[dependencies]
log = "0.4"

[dependencies.w5500-ll]
version = "0.9"
features = ["std"]

[dev-dependencies]
trust-dns-client = "0.20"
w5500-hl = "0.6"
version-sync = "0.9"
nb = "1"
stderrlog = "0.5"
httparse = { version = "1", default-features = false }
