[package]
name = "w5500-regsim"
version = "0.1.0-alpha.1"
authors = ["Alex M. <alexmgit@protonmail.com>"]
edition = "2018"
repository = "https://github.com/newAM/w5500-regsim-rs"
license = "MIT"
description = "Register simulation for the Wiznet W5500 internet offload chip."
readme = "README.md"
keywords = ["spi", "driver", "embedded-hal-driver", "W5500", "wiznet"]
categories = ["embedded", "hardware-support", "no-std"]
homepage = "https://github.com/newAM/w5500-regsim-rs"

[badges]
maintenance = { status = "experimental" }

[dependencies]
lazy_static = "1"
w5500-ll = "0.4"
log = "0.4"

[dev-dependencies]
version-sync = "0.9.1"
